#Section to define paths for the pre-processing
# This section will be used by the scripts under pre_processing
shared:
  start_date: 2021122500
  end_date: 2021122500
  
pre:
  fclen: 48
  vfld_path: /ec/res4/scratch/sp3c/deode_verif/cases/ireland_2021/vfld/
  vobs_path: /ec/res4/scratch/sp3c/deode_verif/cases/ireland_2021/vobs/
  by_vobs_step: 1h
  vfld_template:  #include one for each model if they are different. 
    - vfld
  do_all: TRUE # if true, it will ignore list of parameters and do all that is available in the vfld files
  params:
    - Pcp
    - AccPcp1h
    - AccPcp3h
    - AccPcp6h
    - AccPcp12h
    - AccPcp24h     
    - S10m
    - T2m
    - RH2m
    - Pmsl
    - T
    - Cbase            
    - CChigh         
    - CClow      
    - CCmed        
    - CCtot         
    - D10m   
    - G10m    
    - Gmax  
    - Ps                                                                               
    - Smax               
    - Td2m                       
    - Tmax                                           
    - Tmin                                               
    - vis                
    - DSN
    - SD
    - Q2m

#Section to define paths for the verification
# This section will be used by the scripts under verification
verif:
  by_step: 24h
  fcst_model:
    - deode_ierain_ref
#    - dept_ierain_vhrifs_2500
#    - dept_ierain_ref_2500
  lead_time: seq(0, 48, 1)
  fcst_type: det #det or eps
  grps: leadtime
  fcst_path: /perm/sp3c/DE_330-verif-scripts_phase1/cases/ireland_2021/FCTABLE
  obs_path: /perm/sp3c/DE_330-verif-scripts_phase1/cases/ireland_2021/OBSTABLE
  verif_path: /perm/sp3c/deode_project/DE_330-verif-scripts//cases/ireland_2021/output/verif_results
#Section to define the paths for the output
# This section will be used by the plotting scripts
post:
  plot_output: /perm/sp3c/deode_project/DE_330-verif-scripts//cases/ireland_2021/output
  rds_path: /perm/sp3c/deode_project/DE_330-verif-scripts//cases/ireland_2021/verif_rds
#This section if only for the scorecards
scorecards:
  ref_model: deode_ierain_ref
  fcst_model: deode_ierain_ref
  params: 
    - T2m
    - S10m
    - RH2m
    - Pmsl
    - AccPcp12h          
    - AccPcp6h
    - AccPcp3h
    - AccPcp1h
    - Pcp
    - Cbase                   
    - CClow      
    - CCtot         
    - D10m
    - Gmax    
    - AccPcp1h                                
    - Ps                                                                               
    - Td2m                       
    - Tmax                                           
    - Tmin                                               
    - vis  
