#Section to define paths for the pre-processing
# This section will be used by the scripts under pre_processing
shared:
  start_date: 2022050200
  end_date: 2022050300
  
pre:
  fclen: 24
  vfld_path: "/perm/sp3c/deode_verif/cases/Spain20220503/vfld/"
  vobs_path: "/perm/sp3c/deode_verif/cases/Spain20220503/vobs/"
  by_vobs_step: "3h"
  vfld_template:  #include one for each model if they are different. 
    - "vfld"
  do_all: TRUE # if true, it will ignore list of parameters and do all that is available in the vfld files
  params:
    - Pcp
    - AccPcp1h
    - AccPcp3h
    - AccPcp6h
    - AccPcp12h
    - AccPcp24h     
    - S10m
    - T2m
    - RH2m
    - Pmsl
    - T
    - Cbase            
    - CChigh         
    - CClow      
    - CCmed        
    - CCtot         
    - D10m   
    - G10m    
    - Gmax  
    - Ps                                                                               
    - Smax               
    - Td2m                       
    - Tmax                                           
    - Tmin                                               
    - vis                
    - DSN
    - SD
    - Q2m
#Section to define paths for the verification
# This section will be used by the scripts under verification
verif:
  by_step: "12h"
  fcst_model:
    - AIB_43h221_de
    - VAL500m_de
  lead_time: seq(0, 24, 1)
  fcst_type: "det" #det or eps
  grps: "leadtime"
  fcst_path: "/perm/sp3c/deode_verif/cases/Spain20220503/FCTABLE"
  obs_path: "/perm/sp3c/deode_verif/cases/Spain20220503/OBSTABLE"
  verif_path: "/perm/sp3c/deode_verif/plot_point_verif/cases/Spain20220503/"
#Section to define the paths for the output
# This section will be used by the plotting scripts
post:
  plot_output: "/perm/sp3c/deode_verif/cases/Denmark20201009/output"
  rds_path: "/perm/sp3c/deode_verif/plot_point_verif/cases/Spain20220503"
#This section if only for the scorecards
scorecards:
  ref_model: AIB_43h221_de
  fcst_model: VAL500m_de
  params: 
    - T2m
    - S10m
    - RH2m
    - Pmsl
    - AccPcp12h          
    - AccPcp6h
    - AccPcp3h
    - AccPcp1h
    - Pcp
    - Cbase                   
    - CClow      
    - CCtot         
    - D10m
    - Gmax    
    - AccPcp1h                                
    - Ps                                                                               
    - Td2m                       
    - Tmax                                           
    - Tmin                                               
    - vis  
